### ISSUE TITLE
Intermittent warnings on header newlines

### ISSUE THREAD

**Issue by tomjn** [Rarst/laps#28]
I'm seeing this warning appear in my error logs:

```
E_WARNING [2] Header may not contain more than a single header, new line detected in /srv/www/tomjn.com/htdocs/wp-content/plugins/laps/src/Manager/Server_Timing_Manager.php:67
#1 /srv/www/tomjn.com/htdocs/wp-content/plugins/laps/src/Manager/Server_Timing_Manager.php(67): header('Server-Timing: ...')
#2 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(288): Rarst\Laps\Manager\Server_Timing_Manager->send_timing_header(false)
#3 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(203): WP_Hook->apply_filters(false, Array)
#4 /srv/www/tomjn.com/htdocs/wp-includes/rest-api/class-wp-rest-server.php(372): apply_filters('rest_pre_serve_...', false, Object(WP_REST_Response), Object(WP_REST_Request), Object(WP_REST_Server))
#5 /srv/www/tomjn.com/htdocs/wp-includes/rest-api.php(295): WP_REST_Server->serve_request('/yoast/v1/stati...')
#6 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#7 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#8 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#9 /srv/www/tomjn.com/htdocs/wp-includes/class-wp.php(375): do_action_ref_array('parse_request', Array)
#10 /srv/www/tomjn.com/htdocs/wp-includes/class-wp.php(715): WP->parse_request('')
#11 /srv/www/tomjn.com/htdocs/wp-includes/functions.php(964): WP->main('')
#12 /srv/www/tomjn.com/htdocs/wp-blog-header.php(16): wp()
#13 /srv/www/tomjn.com/htdocs/index.php(17): require('/srv/www/tomjn....')
#14 {main}
URL: tomjn.com/wp-json/yoast/v1/statistics
HTTP_REFERER: https://tomjn.com/wp-admin/index.php?elm-log-cleared=1
uniqid: 5c463a5d014a2
```

Unsure of the cause, but perhaps some sanitising or encoding in `Server_Timing_Manager` might help

**Comment by Rarst** [comment]
Just noticed it this evening as well via Query Monitor complaining on a live site, but don't think I've seen it in my dev environment.

Will look into!

**Comment by Rarst** [comment]
Yep, can't reproduce in dev environment. Curious if you can dump what's causing it if you get a chance.

Meanwhile pushed a fix, will be in next minor release (which should be soon, just want to throw couple minor new features in).

**Comment by Rarst** [comment]
Ah, I got updated version on a live site, previously exhibiting the error, and most likely source of new lines are captured SQL queries. Mystery solved. :)
