### ISSUE TITLE
Laps crashes with Popup-Maker

### ISSUE THREAD

**Issue by lkraav** [Rarst/laps#7]
https://github.com/PopupMaker/Popup-Maker

```
[10-Aug-2015 17:33:54 UTC] PHP Fatal error:  Uncaught exception 'LogicException' with message 'Event "Main Loop" is not started.' in /srv/conversionready/home/warmpress/wp-content/plugins/laps.git/vendor/symfony/stopwatch/Section.php:146
Stack trace:
#0 /srv/conversionready/home/warmpress/wp-content/plugins/laps.git/vendor/symfony/stopwatch/Stopwatch.php(121): Symfony\Component\Stopwatch\Section->stopEvent('Main Loop')
#1 /srv/conversionready/home/warmpress/wp-content/plugins/laps.git/src/class-laps.php(105): Symfony\Component\Stopwatch\Stopwatch->stop('Main Loop', 'theme')
#2 [internal function]: Rarst\Laps\Laps::tick(Object(WP_Query))
#3 /srv/conversionready/home/warmpress/wp-includes/plugin.php(571): call_user_func_array(Array, Array)
#4 /srv/conversionready/home/warmpress/wp-includes/query.php(3760): do_action_ref_array('loop_end', Array)
#5 /srv/conversionready/home/warmpress/wp-content/plugins/popup-maker/includes/load-popups.php(72): WP_Query->have_posts()
#6 [internal function]: popmake_preload_popups('')
#7 /srv/conversionready/home/warmpress/w in /srv/conversionready/home/warmpress/wp-content/plugins/laps.git/vendor/symfony/stopwatch/Section.php on line 146
```

Having trouble figuring out what side the blame lies on. Thoughts?

**Comment by Rarst** [comment]
Hm hm... I think this would happen if it `have_posts()` and it's false, without ever doing `the_post()` on it. Hard to say without seeing what kind of query object it is and what it's doing.

**Comment by lkraav** [comment]
Looks like `popup-maker/includes/load-popups.php` oerhaps

**Comment by Rarst** [comment]
```php
while ( $query->have_posts() ) : $query->next_post();
```
Yeah, this would do it. This is one extremely peculiar query. I am not even sure if this is "wrong" per se, since I had never seen one like this before.

**Comment by lkraav** [comment]
How would you rewrite it? Just replace with `$query->the_post()` since that also calls `next_post()`? I tried it, but it seems to have side effects and breaks the site query flow, though.

**Comment by Rarst** [comment]
I'd just go `get_posts()` / `foreach()` on it. There is no need to loop if there is no need to touch globals.
